### ISSUE TITLE
Web scraping envisalink for autodetection

### ISSUE THREAD

**Issue by rct** [ufodone/envisalink_new#10]
I saw in comments that you are web scraping the envisalink web interface to detect system type and mac address.  While this should be beneficial for convenience, EyezOn is pretty likely to break that at some point. Also their track record for announcing changes to their firmware is poor.  They push out changes, even major unannounced. 

Couldn't this bit of convenience could cause future breakage, that you need a new release of Home Asssistant core to correct?

**Comment by rct** [comment]
Also out of curiosity, what do you need the envisalink's mac address for?

**Comment by ufodone** [comment]
Yes, I've been thinking about them breaking it.  But these devices are also pretty old and I've never actually seen these pages change so it felt relatively safe.

The main reason it does the scraping is to get the MAC address.  Home Assistant requires a [unique ID](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#unique-ids) for entities in order to be able to manage them in the UI.  MAC address is the only viable option for the EVL other than using the config entry ID (which, I think is meant as a last resort).

The other thing I may do is use discovery for initial setup but store the values in the config entry.  That way if EyezOn breaks the scraping, existing setups will continue to work but new setups will not.

**Comment by rct** [comment]
There have been some recent changes to those pages.  What firmware version(s) are you testing with?

From [EyezOn's firmware change log on their forum](https://forum.eyezon.com/viewtopic.php?t=5115) 

* 1.4.183 - the "Home" page (/2) was changed to remove all of DSC zone status stuff.

**Comment by ufodone** [comment]
I'm on 1.4.182.  I haven't heard of issues from anyone else who's tested but don't know what versions they are running. 

I do know it's also been tested successfully against 1.12.205A on an EVL3.

I suspect I can actually do away with the need for the hardware version since the place it is used could derive its decisions differently.  I could probably also auto-detect the panel type based on the initial data received after connecting.  The firmware version is mostly a nice to have.  So most of this stuff could probably be made optional.  It's really the MAC address I'd love to be able to get reliably.

**Comment by ufodone** [comment]
The next release will no longer depend on discovery (querying port 80/8080) to startup.

It will still be required to create a new device (to obtain the MAC address to use as the unique ID).

This should protect existing setups against firmware updates that might break the web scraping.

The panel type is now auto-detected via port 4025 rather than depending on info from the scraping.
