### ISSUE TITLE
0.4.0 Update duplicated devices and entities

### ISSUE THREAD

**Issue by schmuy** [ufodone/envisalink_new#11]
Updated to v0.4.0 and the integration had duplicated devices and entities so that nothing that referenced the original entities would update/automate.  Deleting integration and restarting fixed the issue.

Unfortunately I wasn't paying attention to what version I was on before.

At some point I had commented out the "envisalink_new:" section in configuration.yaml so it's possible maybe it was related to that?  I deleted the integration, removed the comment block and restarted and everything came back properly.

**Comment by ufodone** [comment]
If you were on an oldish version this might not surprise me. I've been making quite a few changes around the config flow to try and tidy it up and be more robust.  But I also haven't been versioning the config entry during this process so it's possible you had an older version which was incompatible.  Once I get this back into Home Assistant proper I'll need to start versioning the config entry but I've been skipping that during development to save time (and not end needing to support a pile of obsolete versions).

Even if you don't know what version you were coming from, do you have a sense of about how old it was?

> At some point I had commented out the "envisalink_new:" 

Do you mean that you did this during the process of upgrading to 0.4.0?

**Comment by schmuy** [comment]
I would have likely been on 3.1 or 3.4 I think.

With config.yaml it would have been in the past 2 days (this weekend has been a blur).  I just don’t recall if I actually restarted HA after commenting it out, so doing the update might have been the first restart

**Comment by ufodone** [comment]
>I guess in my mind I figured it imported the info from configuration.yaml so I didn’t need to keep it there and could clean it up.

It's true that once it has imported, you can remove it from configuration.yaml.  If you leave it in place, then on startup, it will compare configuration.yaml against what's in the config entry and apply any updates if necessary.  

The one thing to note is that if you were to subsequently remove the device and then re-add it via the UI, you would get the default entities names (which will comply with Home Assistant guidelines).  You will not get your custom names entities back from the configuration.yaml (since you removed it from the file).  You could always rename them in the UI after the fact though.

Generally speaking it's been a bit awkward trying to figure out how to update the integration to modern Home Assistant standards while trying not to break existing users of the integration.  

When I get a chance I'll try a couple upgrades to 0.4.0 to see if I can reproduce what you saw to make sure it's not just the lack of versioning of the config I mentioned above.

**Comment by ufodone** [comment]
Ha!  I just tried to update my own, "production" system and got the same thing.
