### ISSUE TITLE
DSC PGM output not working

### ISSUE THREAD

**Issue by nickb24** [ufodone/envisalink_new#115]
I just updated from the HA integration to this new one but I can't get my PGM output service call to to work anymore. I have a DSC panel with an EVL4.

I've done some debugging, and I found this in the logs:

> 2024-06-02 21:22:29.247 DEBUG (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] calling handler: handle_send_code for code: 900 with data: 
2024-06-02 21:22:29.247 DEBUG (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] No handler configured for evl command.
2024-06-02 21:22:29.247 DEBUG (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] KeyError: 'DSCClient' object has no attribute 'foo'
2024-06-02 21:22:29.247 DEBUG (MainThread) [custom_components.envisalink_new.pyenvisalink.envisalink_base_client] Invoking state change callbacks

It looks like it's not handling the 900 command which is asking for a code. Also, in the HA integration I didn't have to put a code in the service call as it would use the user code from the configuration.yaml, is this needed for this new integration too?

This was what my old service call looked like that works in HA native integration:
![image](https://github.com/ufodone/envisalink_new/assets/2193756/83913ba2-1706-4aae-9b02-3bd4c1e2b6b4)

This is the new one that doesn't work with envisalink_new:
![image](https://github.com/ufodone/envisalink_new/assets/2193756/f66d677d-ab5e-4f48-b889-0f07d7eab8b3)

**Comment by ufodone** [comment]
I've published a v0.9.1 release which I think should fix this issue.  I don't have PGM outputs setup on my own panel but there was a fairly obvious bug in the code which I suspect was the issue.  Please let me know if this correct the problem for you.

**Comment by ufodone** [comment]
> The 660 command was already received, so it looks the PGM is already activated and working. So no need to respond to the 912 command.

Presumably the EVL wants the code for something though.  From your logs, it sends a 900 requesting the code first which the integration responds to so I'm not sure why it's requesting it a second time via the 912.  The 900 is just a generic "please give me the code" request where as 912 is specific to the PGM and the request includes the partition and command output the code is requested for.

Rather than commenting out processing of the 912, I think it would be safer to actually respond to it.  Or at least try that and see what happens.

I think your second change to switch `send_command` to `queue_command` should be fine.  I wasn't able to reproduce this setup so wasn't sure what the command sequence would look like so I played it safe with `send_command`.  Now that I see the logs, `queue_command` makes sense.

**Comment by ufodone** [comment]
Thanks, @nickb24 .  I'll try and get these changes in shortly.

**Comment by ufodone** [comment]
I had a deeper look at your changes and had some questions.

The processing you added for the `912` command it introducing a new status attribute called `CommandOutput`.  This seems redundant to the `PGMrelay` attribute that is added when the `660` command received from the EVL.

And I don't see where either `PGMrelay` or `CommandOutput` would ever been cleared.  I'm not familiar with how the PGMs are meant to work.  Are they something you toggle on/off or they a momentary switch or something else?  If there isn't a way to know when they are "cleared" then I think the `PGMrelay` and `CommandOutput` attributes should be removed completely.  The same *might* apply for the alpha update as well although it will get updated by other commands such as the partition changing state.

**Comment by ufodone** [comment]
Given that variety of behaviours, maybe it makes the most sense to remove the `PGMrelay` (and your new `CommandOutput`) attribute and add a new timestamp attribute indicating when the PGM was last triggered.  This could be updated by the `912` command.  What do you think?

**Comment by ufodone** [comment]
I've push the [changes](https://github.com/ufodone/envisalink_new/commit/d01d95d630ebdeb0f0c53787408c0c584f5386ff) discussed above to main.  If you're able, can you give them a try by installing the `main` version of the integration?

**Comment by ufodone** [comment]
I removed 660 because there didn't seem to be anything I could do with it other than just ignore it.  660 only indicates which partition a PGM was triggered on where as 912 gives the partition and PGM output so I figured I'd just use 912.  The "No handler" message is just debug so won't show up at normal logging levels.

Thanks for confirming things work.
