### ISSUE TITLE
unavailable more so then regular integration

### ISSUE THREAD

**Issue by dasb00ter** [ufodone/envisalink_new#129]
![Screenshot_2024-07-24-12-54-09-993_io homeassistant companion android](https://github.com/user-attachments/assets/e0b12eef-bf01-49da-8e4a-4245c1d7c74c)
![Screenshot_2024-07-24-12-54-09-993_io homeassistant companion android](https://github.com/user-attachments/assets/e0b12eef-bf01-49da-8e4a-4245c1d7c74c)
This may be a networking issue but I was just hoping you might be able to help. I've had a problem with the stock integration periodically but I'm now experiencing a completely unusable situation with envisalink new installed through hacs. I believe the hardware I have is box branded connect2go which I believe is the evl4. I will see if I can update the firmware. I'm using an enterprise class brocade switch and an r8000 router with tomato on it. Any insight would be helpful

**Comment by ufodone** [comment]
Most cases where I've seen this behaviour has been due to older firmware on the EVL4 causing them to go unresponsive for upwards of 30s.  I have seen the odd case where it seemed to be network related but I suspect that in those cases it was likely other traffic on the network triggering the firmware to go unresponsive (e.g., by making queries to the device).  In these cases, this integration tends to "show" the issue more frequently than the stock one because when it makes a request to the EVL, it expects a response.  The stock integration does not.  

So definitely check your firmware version first.

It would be helpful if you could enable debug logging for the integration and provide those logs for a period that spans across when it goes unresponsive (some number of minutes on either side of the event would be helpful).  That could help narrow down whether it's an issue with the integration itself or something network/firmware/etc. related.

**Comment by dasb00ter** [comment]
I will try if the firmware is not the latest or doesn't fix. I'll have to read up on debugging an integration. It's been awhile

**Comment by ufodone** [comment]
@dasb00ter Is this still an issue for you?

**Comment by dasb00ter** [comment]
AHH idk how to answer. I changed the cat 5 cable from the card my switch and it improved. I still have times where it is unavailable. I believe I am on the latest firmware. That is a bit of a rabbit hole that I went down. I'm going to close this as I feel like I should be doing more work to debug... But I'm new parent and it's livable
