### ISSUE TITLE
Request to Add PGM1 through PGM4

### ISSUE THREAD

**Issue by BobRobertBob** [ufodone/envisalink_new#132]
Completely new to Home Assistant and to Github so please bear with me.  Not sure where to post this but here goes.
I have installed Envisalink Refactored (replacing the original Envisalink Integration) and it’s working flawlessly.  No more zones changing state randomly, as well some additional features.  Thank you for developing this application, it’s really the core of my automations (I have a lot of zones).
I would like to request that you consider an additional feature.  I use a “Program Output” to energize a solenoid that opens a door.  In my case I am using PGM1, but there are 4 outputs available (PGM1 through PGM4) on DSC panels.  So, an entity for each of the 4 PGM outputs such that they could be energized via a button or automation.
Currently, I am doing this through the EyezOn app but being able to do it through Home Assistant would be cleaner and easier.  Thank you for considering this and let me know if should be directing this somewhere else.

**Comment by ufodone** [comment]
Hi, because the PGMs can be programmed on the panels to have a variety of different behaviours, I'm not sure that adding explicit switches to the integration would make sense because the behaviour (and state) of the switch might not properly reflect how the PGMs are setup on the panel.

However, I think you could achieve what you want by using a [template switch](https://www.home-assistant.io/integrations/switch.template/) and map the toggle or on/off actions to the `Envisalink_new: Invoke custom function` service call to trigger the appropriate PGM.  You could then template the value to represent what makes sense for your setup.

**Comment by BobRobertBob** [comment]
Thank you for your help, that worked perfect.  I didn't realize that the custom function to trigger PGM was an option.  Again, great integration, no more phantom zone toggles.
