### ISSUE TITLE
Bypassed zone shows as clear

### ISSUE THREAD

**Issue by doppiaemme** [ufodone/envisalink_new#135]
Hi,
Envisalink 3 with a dsc panel.
I bypassed a zone with the integration then armed away.
The zone is showing as clear, not bypassed on the integration while it correctly shows a bypass in the envisalink app.
Is this a known issue?
Even reloading doesn't fix the status.
Thanks

**Comment by ufodone** [comment]
The zone binary_sensors reflect whether a zone is open or closed.  The zone bypass switches reflect whether a zone is bypassed or not.  They are not combined as a single sensor because they are indicating different things.  E.g., a zone can be bypassed and open or bypassed and closed.

Someone [here](https://github.com/ufodone/envisalink_new/issues/35#issuecomment-1601380793) posted an example where they use a mushroom template card to combine zone state and bypass state using different colours which might be something along the lines of what you're looking for.

**Comment by doppiaemme** [comment]
Hi,
Sorry I didn't explain well my issue.
The zone bypass switch shows the zone as not bypassed, however it isbypassed, and indeed the envisalink app shows is correctly as bypassed.
To bypass it initialky, I used your integration. But once done, the status is not reported correctly afterwards. In practical the integration is showing me all the zones as not bypassed, while one is in reality bypassed. 
In the  screenshot here below, this zone is bypassed but it doesn't show it.
I hope it makes more sense.
![IMG_3441](https://github.com/user-attachments/assets/7c6fca2e-4d8e-4c59-ba05-b2dd6a51a15d)

**Comment by ufodone** [comment]
Ah, okay.  I just tried on my system and it seems to work.  Can you enable debug logging for `envisalink_new` and post the logs?  If you could turn on the debug logging and then restart HA and once it's come up, try and bypass a zone using the bypass switch a few times.  That should hopefully provide enough info to figure out what's going on.

**Comment by ufodone** [comment]
@doppiaemme I haven't heard anything back from you for several months.  If this is still an issue, feel free to re-open and provide the requested logs.
