### ISSUE TITLE
first feedback, not working when using the alarmserver proxy

### ISSUE THREAD

**Issue by tinuva** [ufodone/envisalink_new#2]
first feedback, not working when using the alarmserver proxy in-between the EVL4 and HA.

The proxy works fine with the stock envisalink integration, but I suspect this new version is also trying to do something else?

![Screenshot 2023-01-11 at 18 12 48](https://user-images.githubusercontent.com/5417682/211858355-57dfc601-b383-4be9-ab5d-366707f073c3.png)

![Screenshot 2023-01-11 at 18 13 41](https://user-images.githubusercontent.com/5417682/211858367-ee50c069-f7e5-4d1e-b7c7-386e4d6d604c.png)

I suspect the next step is to enable logging and see whats happening.

So for now I only see:
```
Logger: root
Source: custom_components/envisalink_new/pyenvisalink/alarm_panel.py:212
Integration: Envisalink_new
First occurred: 6:05:48 PM (2 occurrences)
Last logged: 6:12:44 PM

Panel type could not be determined.
```

**Comment by tinuva** [comment]
Yup I think it is also connecting to port 80

```
        try:
            async with aiohttp.ClientSession(auth=aiohttp.BasicAuth(self._username, self._password)) as client:
                url = f'http://{self._host}/2'
```

**Comment by ufodone** [comment]
Yes, it tries to connect to the EVL on port 80 as well to discover the EVL version, panel type, firmware version and, more importantly, the MAC address of the device.  The latter is used for the unique ID in HA so that the entities can be exposed and managed via the UI.  It can call back to using the config entry ID if the MAC isn't obtainable.

I wanted to try and simplify the configuration as much as possible but could add explicit configuration for the EVL version and panel type back in and make them optional which should allow you to continue to use the alarm server proxy as-is.  It would necessarily fall back to using the config entry ID for the unique ID though.  I think the downside of that is that if you remove the device and then re-add it, it will get a new unique ID so any history on the entities would not be reconnected to the newly created ones because the unique ID would have changed (I'm just speculating on that though).

An alternative might be to add port 80 forwarding support to alarm server proxy.

**Comment by tinuva** [comment]
ok before you go through all that work, I may be in the minority for this. Will look at a work-around which doesn't require port 80 in the alarmserver proxy. I have an idea, which I just need to test out first when I have some time.

**Comment by ufodone** [comment]
A couple other thoughts:

1. Add a "proxy host" configuration which would be used for one or both of the connections.  That might allow you to forward 4025 to AlarmServer but 80 directly to the EVL.
2. Add the ability to specify both ports.  While this doesn't magically fix the issue, it would allow you to use a port outside the privileged range (1-1023) which might make proxying easier.  You could use a separate proxy to forward that connection rather than needing to modify AlarmServer.  Not ideal to have to run an additional proxy though.

**Comment by tinuva** [comment]
Alright I was able to get the addon to connect up in parallel with the original addon and this addon at the same time.

On the VM running alarmserver, I already had traefik running on port 80/443 for other containers. I just had to add a manual host for the envisalink and set up dns in my home network for it. The goodnews is, configuring a hostname in the addon works so that was all I needed to do.

![Screenshot 2023-01-13 at 08 10 42](https://user-images.githubusercontent.com/5417682/212250048-5509c384-40c0-48fc-9049-dcbf86d09ad3.png)

**Comment by ufodone** [comment]
Glad you were able to get something working.  I may still add the ability to override port 80 to make it easy to avoid port conflicts if a shared proxy is used where port conflicts may exists.  It would also be useful for my own testing as well against a mock-EVL I've been working on.

**Comment by ufodone** [comment]
@tinuva The latest release accidentally ended up using port 8080 instead of 80 for the discovery.  I'd been using this for local testing against a mock server but it turns out the the EVL is listening on both port 80 and 8080.  Are you able to adjust your setup to use port 8080?  Just checking because I think I'd prefer to leave it at 8080 since it works on the actual EVL hardware and it would avoid me making mistakes (like now) and committing the code with a different port.
