### ISSUE TITLE
Zone last_tripped_time attribute

### ISSUE THREAD

**Issue by rct** [ufodone/envisalink_new#21]
What's the intended behavior of the `last_tripped_time` attribute of a zone's binary_sensor?

It looks like the current behavior is that  unless a zone has opened, it shows the time when the integration connected to the envisalink.  Seems very similar (maybe a duplicate) of the entity's base attributes `last_updated` and `last_changed`)

**Comment by ufodone** [comment]
These are driven by the zone timer dumps.  I can't say what the original intent was (I'm not the original author) but I assume they are meant to show the last time a zone was faulted.  That's going to be different than the `last_updated` or `last_changed` times because they would be updated when a zone clears as well.
