### ISSUE TITLE
what is panel chime?

### ISSUE THREAD

**Issue by progamer562** [ufodone/envisalink_new#43]
![image](https://github.com/ufodone/envisalink_new/assets/75967844/3b40d6d8-3c14-4214-8d4a-9c3f4cfc5cd5)
if i turn it on nothing happends

**Comment by davecpearce** [comment]
I noticed this too. It turns on/off the keypad chimes when a zone opens or closes. I had to change this directly on the keypad before, I find this useful having it in HA now.

**Comment by progamer562** [comment]
I tried turning this on nothing happens must be the zone chime disabled.

**Comment by davecpearce** [comment]
My zone chime was on at the keypad but the sensor was initially set to off when I added the integration. When I turned the chime on, and then off in HA, the zone chime turned off on the keypad for me.

**Comment by ufodone** [comment]
@davecpearce Do you have a DSC panel?  If so, what you’re seeing is unfortunately normal since DSC systems don’t appear to provide a way to query the current chime state which means that HA cannot tell what to set the switch to on initial startup.  However, the integration will preserve the state between HA restarts so once it’s in the correct state in HA relative to the panel itself, then the behavior should be correct as long as you don’t toggle the chime from a physical panel while HA is not running.

**Comment by jhenkens** [comment]
Panel Chime switch only works if the code is entered into the configuration. Might want to not show that entity unless code is present.

**Comment by ufodone** [comment]
@jhenkens Thanks for the suggestion.  I've added it to [v0.7.1](https://github.com/ufodone/envisalink_new/releases/tag/v0.7.1)
