### ISSUE TITLE
Slow response on closing contacts and clearing motions

### ISSUE THREAD

**Issue by franquosino** [ufodone/envisalink_new#45]
I install Envisalink_new as a new install for my Honeywell panel a few months ago now and it has worked quite well. 

I can see when opening a door that the response is almost instanteneous. However, it may take up to 20 seconds to report the door's status when closed, showing opened all the while. Similarly, the motion sensors report detections rapidly, but it may take up to 40 seconds to clear after motion has stopped. 

This may  have been the fact since the initial installation, but I just noticed it recently. 

Otherwise, no errors or warnings in the log files. Likewise, all related automations work as expected. 

Any thoughts?

**Comment by ufodone** [comment]
Hi, unfortunately this is likely expected behaviour on Honeywell panels.  The Honeywell panels don't explicitly report zones closing so it's necessary to infer that information based on the keypad updates the panels do provide.  The amount of time before a zone is detected as cleared is impacted by the number of zones that are currently faulted.  E.g. if you only have one zone faulted and then you clear it, then that should be reflected in HA almost immediately.  If, on the other hand, you have 4 zones faulted and one of them clears, you may not see the zone being cleared for maybe 20+ seconds.  

If you want the gory details, there's a good description starting [here](https://github.com/ufodone/envisalink_new/issues/9#issuecomment-1410972022).

**Comment by franquosino** [comment]
Thank you for the explanation. I read the "gory details" and have a better appreciation for the issue. I can live with it.

Thanks again for putting together this great integration.
