### ISSUE TITLE
Flow aborted: already_configured when renaming existing integration in config

### ISSUE THREAD

**Issue by ptr727** [ufodone/envisalink_new#60]
Got an error `Flow aborted: already_configured` during setup:

- had an existing envisalink config in yaml.
- renamed it from `envisalink` to `envisalink_new`
- installed the new integration using HACS
- restarted HA
- added the new integration
- got prompted for config, not expected, though config would use existing yaml config, e.g. did not pick up host, password, zones, etc.
- manually entered information
- clicked submit and got `Flow aborted: already_configured` error
- aborted config
- refreshed HA and saw integration was already added, and it did use config from YAML

When adding new integration and importing existing config from yaml, config UI should not be shown, or should be shown in edit mode based on imported settings.

**Comment by ufodone** [comment]
When you say `add the new integration`, do you mean clicking the `Add Integration` button in `Settings->Devices & service`?  If so, that is unnecessary if you have the `envisalink_new` in your configuration.yaml as it will automatically add the integration for you.

I suspect what happened is that after the restart, the envisalink device was automatically setup and then when you tried to add the integration a second time, it was attempting to set up a second device.  The `already configured` error was because the configuration.yaml setup had already been imported and configured.

**Comment by ptr727** [comment]
Yes, the way I understood the instructions was to add an integration and it would import the settings, if it automatically added the integration then that may be the issue, maybe update the readme to elaborate on the migration path not needing to add the integration.

**Comment by etiennevanderpoel** [comment]
I ran into the same error message when I had to restore a backup (for a different problem). _envisalink_new_ was already configured, but was then re-discovered when HA booted up. The existing _envisalink_ integration is working fine (nice work, ufodone), but the integration still shows a Discovered card as if there is a new integration.

Is there a way to make this card and notification go away?

**Comment by denix0** [comment]
FWIW, maybe it has been fixed already, but I just went through this exercise of replacing an existing Envisalink integration with the Refactored one. I installed it from HACS, renamed `envisalink` with `envisalink_new` in config and rebooted. Initially it showed that a new device has been discovered, but it quickly cleared up within seconds of booting up.

Since I've made additional configuration changes since then (Area assignments, etc), I assume that I can remove the entire section from the `configuration.yaml` file - the new config is not kept there, right?

**Comment by ufodone** [comment]
@etiennevanderpoel That discovery card is likely showing up because it sees your `envisalink_new` configuration in configuration.yaml but the config entry that matches doesn't have a source value of `import` indicating the entry was created from this config.  It's possible that the act of restoring the backup could have changed the source value but I don't really know how backup/restore works with respect to this.

You could confirm this by looking for the `envisalink_new` entry in your `.storage/core.config_entries` file (in the config directory) and see what the `source` value is set to.

I'm assuming that you have both the correctly configured device and this newly discovered one?  If so, then to fix the problem, removing the `envisalink_new` section from your configuration.yaml should fix the problem.

@denix0 Yes, once the configuration has been successfully imported and your device is working, I'd recommend removing the configuration from configuration.yaml and do future configuration through the UI.
