### ISSUE TITLE
Any sense of when `envisalink_new` will be “ready” to replace the existing integration?

### ISSUE THREAD

**Issue by irace** [ufodone/envisalink_new#83]
Hello,

First, thank you for all of your hard work on this!

I recently installed an EL4 and the classic `envisalink` integration and am running into [this same issue](https://github.com/home-assistant/core/issues/104287) of alarm/disarm working fine from the Envisalink website but not working at all from Home Assistant.

It seems like the classic `envisalink` integration is just broken in this regard, but that `envisalink_new` fixes that particular problem.

That said, I'm wary to upgrade given that `envisalink_new` is still WIP.

Is there an expected timeframe during which development on `envisalink_new` will complete? That would help me make a more informed decision as to how to proceed here.

If it's still going to be a while, is there any chance that the bug in the traditional `envisalink` integration could be looked at?

Thank you!

**Comment by ufodone** [comment]
I no longer consider this version to be a work in progress but I've just failed up update the main page to reflect that.  :smile:  While it's unlikely these version will make it back into HA core to replace the the existing one, I do believe it is in a solid state to be used.  There are a fair number of people who have switched over to it.

Regarding the issue in the core `envisalink` integration,  I don't think it is broadly broken as I just tried it against by own DSC panel and it worked fine.  It may be something specific to some setups that is causing trouble (e.g. maybe longer/shorter alarm code length, certain panel types, specific firmware versions, etc.).  If you turn on debug logging and capture the issue, I can have a look.  Please note though that the `envisalink` version will log your EVL password and alarm code with debugging logging turned on so please either redact those values from the logs before you post them or change your password and code to something temporary before testing.

I also recall some people having troubles with a new firmware version that EyezOn pushed to some devices.  That issue was causing different issues but I think it happened around the time some people started having troubles with the issue you mention so it's possible it could be related.

To turn on debug logging, add to your configuration.yaml:

```
logger:
  default: info
  logs:
    homeassistant.components.envisalink: debug
    pyenvisalink: debug
```

and then restart HA.

**Comment by irace** [comment]
@ufodone Thanks a ton for responding. Last time I enabled debug logging, I didn't see anything that jumped out as remotely interesting but I will try again sometime this week when I have a chance.

> it's unlikely these version will make it back into HA core to replace the the existing one

That's surprising/disappointing to hear. Would you mind elaborating on this? It seems suboptimal for the new/ostensibly “better” version to forever be a lesser-known fork.

**Comment by ufodone** [comment]
> Would you mind elaborating on this? 

I starting these changes just planning to add config flow support and it sort of spiralled into much more significant changes.  By the time I was done, a lot had been upgraded and the scope of the changes were too large for HA to accept them back as a single PR.  In order to get the changes back, I would need to take it all apart and put it back together in small PRs with localized changes.  I just don't have the time to do that.

**Comment by irace** [comment]
Makes total sense, thanks for clarifying.

I'm a bit new here but that suggests that, over time, `envisalink` and `envisalink_new` will likely continue to drift further apart, which puts new adopters like myself in an interesting position.

Hopefully I can get some helpful logs to you and we can figure out how to fix this particular issue in the core `envisalink` integration to at least give me a choice :)
